version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${REPOSITORY_NAME}"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "nginx"
          cluster-name: "${APP_NAME}-cluster"
          service-name: "${APP_NAME}-service"
          container-image-name-updates: "container=nginx,image-and-tag=${CIRCLE_SHA1}:${CIRCLE_SHA1}"

